[package]
name = "vr-lab"
version = "0.1.0"
authors = ["Mick van Gelderen <mickvangelderen@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
glutin = "0.19.0"
gl = "0.11.0"
openvr = { git = "https://github.com/mickvangelderen/openvr-rust", branch = "0.1.x" }
 
[patch."https://github.com/mickvangelderen/openvr-sys-rust"]
openvr-sys = { path = "../openvr-sys-rust" }

[patch."https://github.com/mickvangelderen/openvr-rust"]
openvr = { path = "../openvr-rust" }

[profile.dev]
opt-level = 2
