[global]
diffuse_srgb = true
rain_drop_max = 10000

mode = "Normal"
# mode = "Record"
# mode = "Replay"

scene_path = "bistro/Bistro_Exterior.bin"
# scene_path = "sun_temple/SunTemple.bin"

sample_count = 1
# sample_count = 2
# sample_count = 4
# sample_count = 8
# sample_count = 16

[record]
path = "recording.bin"

[replay]
run_count = 4
path = "recording.bin"

[profiling]
display = true
record_frames = false
path = "profiling.bin"

[window]
vsync = false
srgb = true
rgb_bits = 24
alpha_bits = 8
width = 1280
height = 720

[gl]
framebuffer_srgb = true

[clustered_light_shading]
# projection = "Orthographic"
projection = "Perspective"
# grouping = "Individual"
grouping = "Enclosed"
orthographic_sides = { x = 1.5, y = 1.5, z = 1.5 }
perspective_sides = { x = 8.0, y = 8.0, z = 2.0 }
max_clusters = 16777216 # 2^24 u32 64MB (count_fragments turns active_cluster_ids)
max_active_clusters = 1048576 # 2^20 u32 4MB * (cluster index, light counts, light offsets)
max_light_indices = 1048576 # 2^20 u32 4MB * (light index)

[virtual_stereo]
enabled = false
pitch_deg = 0.0
yaw_deg = 5.0

[camera]
maximum_smoothness = 0.80

[main_camera]
z0 = -0.4
z1 = -100.0
positional_velocity = 8.0
angular_velocity = 0.4
zoom_velocity = 0.5

[debug_camera]
z0 = -0.4
z1 = -3000.0
positional_velocity = 32.0
angular_velocity = 0.4
zoom_velocity = 0.5

[prefix_sum]
pass_0_threads = 128
pass_1_threads = 128
