[global]
diffuse_srgb = true
framebuffer_srgb = true
rain_drop_max = 10000

[window]
vsync = false
srgb = true
rgb_bits = 24
alpha_bits = 8
width = 1280
height = 720

[clustered_light_shading]
# projection = "Orthogonal"
projection = "Perspective"
grouping = "Individual"
# grouping = "Enclosed"
cluster_side = 20.0
max_clusters = 16777216 # 2^24 u32 64MB (fragments_per_cluster turns active_cluster_ids)
max_active_clusters = 1048576 # 2^20 u32 4MB * (cluster index, light counts, light offsets)
max_light_indices = 1048576 # 2^20 u32 4MB * (light index)

[virtual_stereo]
enabled = false
pitch_deg = 0.0
yaw_deg = 5.0

[camera]
maximum_smoothness = 0.80

[main_camera]
z0 = -0.2
z1 = -80.0
positional_velocity = 8.0
angular_velocity = 0.4
zoom_velocity = 0.5

[debug_camera]
z0 = -0.2
z1 = -200.0
positional_velocity = 16.0
angular_velocity = 0.4
zoom_velocity = 0.5

[prefix_sum]
pass_0_threads = 128
pass_1_threads = 128
