[clustered_light_shading]
cluster_side = 5.0

[camera]
maximum_smoothness = 0.80

[main_camera]
positional_velocity = 8.0
angular_velocity = 0.4
zoom_velocity = 0.5

[debug_camera]
positional_velocity = 8.0
angular_velocity = 0.4
zoom_velocity = 0.5